<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Common\Provider;
use App\Models\Common\ProviderVehicle;
use App\Models\Common\ProviderService;
use App\Models\Common\User;
use App\Models\Common\Country;
use App\Models\Common\State;
use App\Models\Common\City;
use App\Models\Common\Menu;
use App\Models\Common\MenuCity;
use App\Models\Transport\RideDeliveryVehicle;
use App\Models\Transport\RideType;
use App\Traits\Encryptable;
use Carbon\Carbon;

class DemoTableSeeder extends Seeder
{
	use Encryptable;
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run($company = null)
	{
		Schema::disableForeignKeyConstraints();

		$country = Country::where('country_code', 'US')->first();
		$washington_state = State::where('state_name', 'Washington')->where('country_id', $country->id)->first()->id;
		$city = City::where('city_name', 'Charleston')->where('state_id', $washington_state)->first();

		$users = [
			[
				'first_name' => 'User',
				'last_name' => 'Demo',
				'unique_id' => 'USR1',
				'email' => 'demo@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543210',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB001',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'provider',
				'last_name' => 'Demo',
				'unique_id' => 'USR2',
				'email' => 'brayden@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543211',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB002',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'James',
				'last_name' => 'Demo',
				'unique_id' => 'USR3',
				'email' => 'cina@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543212',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB003',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Emily',
				'last_name' => 'Demo',
				'unique_id' => 'USR4',
				'email' => 'kain@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543213',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB004',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Jack',
				'last_name' => 'Demo',
				'unique_id' => 'USR5',
				'email' => 'rigo@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543214',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB005',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Conor',
				'last_name' => 'Demo',
				'unique_id' => 'USR6',
				'email' => 'sumi@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543215',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB006',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Amelia',
				'last_name' => 'Demo',
				'unique_id' => 'USR7',
				'email' => 'vithin@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543216',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB007',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Adam',
				'last_name' => 'Demo',
				'unique_id' => 'USR8',
				'email' => 'marco@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543217',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB008',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Liam',
				'last_name' => 'Demo',
				'unique_id' => 'USR9',
				'email' => 'dani@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543218',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB009',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Noah',
				'last_name' => 'Demo',
				'unique_id' => 'USR10',
				'email' => 'stefen@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543219',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB010',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Emma',
				'last_name' => 'Demo',
				'unique_id' => 'USR11',
				'email' => 'devin@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543220',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB011',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Nia',
				'last_name' => 'Demo',
				'unique_id' => 'USR12',
				'email' => 'hugo@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543221',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB012',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Diegi',
				'last_name' => 'Demo',
				'unique_id' => 'USR13',
				'email' => 'diego@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543222',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB013',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Booker',
				'last_name' => 'Demo',
				'unique_id' => 'USR14',
				'email' => 'booker@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543223',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB014',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Cillian',
				'last_name' => 'Demo',
				'unique_id' => 'USR15',
				'email' => 'arizona@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543224',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB015',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Imala',
				'last_name' => 'Demo',
				'unique_id' => 'USR16',
				'email' => 'imala@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543225',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB016',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Beyon',
				'last_name' => 'Demo',
				'unique_id' => 'USR17',
				'email' => 'beyon@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543226',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB017',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Lutana',
				'last_name' => 'Demo',
				'unique_id' => 'USR18',
				'email' => 'lutana@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543227',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB018',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Mirri',
				'last_name' => 'Demo',
				'unique_id' => 'USR19',
				'email' => 'mirri@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543228',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB019',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Gough',
				'last_name' => 'Demo',
				'unique_id' => 'USR20',
				'email' => 'gough@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543229',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB020',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Voss',
				'last_name' => 'Demo',
				'unique_id' => 'USR21',
				'email' => 'voss@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543230',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB021',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Lucinda',
				'last_name' => 'Demo',
				'unique_id' => 'USR22',
				'email' => 'lucinda@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543231',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB022',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Melba',
				'last_name' => 'Demo',
				'unique_id' => 'USR23',
				'email' => 'melba@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543232',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB023',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Clancy',
				'last_name' => 'Demo',
				'unique_id' => 'USR24',
				'email' => 'clancy@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543233',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB024',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Hart',
				'last_name' => 'Demo',
				'unique_id' => 'USR25',
				'email' => 'hart@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543234',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB025',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Chet',
				'last_name' => 'Demo',
				'unique_id' => 'USR26',
				'email' => 'chet@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543235',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB026',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Win',
				'last_name' => 'Demo',
				'unique_id' => 'USR27',
				'email' => 'win@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543236',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB027',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Coltran',
				'last_name' => 'Demo',
				'unique_id' => 'USR28',
				'email' => 'coltran@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543237',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB028',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Tobiah',
				'last_name' => 'Demo',
				'unique_id' => 'USR29',
				'email' => 'tobiah@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543238',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB029',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Sybil',
				'last_name' => 'Demo',
				'unique_id' => 'USR30',
				'email' => 'sybil@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543239',
				'gender' => 'MALE',             
				'company_id' => $company,
				'country_id' => $city->country_id,
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB030',
				'qrcode_url' =>'',
			]
		];

		foreach ($users as $user) {
			User::create($user);
		}

		

		$providers = [
			[
				'first_name' => 'Provider',
				'last_name' => 'Demo',
				'unique_id' => 'PRV1',
				'email' => 'demo@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543210',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB001',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Fabian',
				'last_name' => 'Demo',
				'unique_id' => 'PRV2',
				'email' => 'fabian@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543212',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB002',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Britt',
				'last_name' => 'Demo',
				'unique_id' => 'PRV3',
				'email' => 'britt@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543213',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB003',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Llse',
				'last_name' => 'llse',
				'unique_id' => 'PRV4',
				'email' => 'britt@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543214',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB004',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Tess',
				'last_name' => 'Demo',
				'unique_id' => 'PRV5',
				'email' => 'tess@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543215',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB005',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Dunnya',
				'last_name' => 'Demo',
				'unique_id' => 'PRV6',
				'email' => 'dunya@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543216',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB006',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Gwen',
				'last_name' => 'Demo',
				'unique_id' => 'PRV7',
				'email' => 'gwen@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543217',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB007',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Stacy',
				'last_name' => 'Demo',
				'unique_id' => 'PRV8',
				'email' => 'stacy@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543218',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB008',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Hudson',
				'last_name' => 'Demo',
				'unique_id' => 'PRV9',
				'email' => 'gwen@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543219',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB009',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Ned',
				'last_name' => 'Demo',
				'unique_id' => 'PRV10',
				'email' => 'ned@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543220',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB010',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Bridger',
				'last_name' => 'Demo',
				'unique_id' => 'PRV11',
				'email' => 'bridger@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543221',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB011',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Alfred',
				'last_name' => 'Demo',
				'unique_id' => 'PRV12',
				'email' => 'alfred@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543222',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB012',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Blake',
				'last_name' => 'Demo',
				'unique_id' => 'PRV13',
				'email' => 'blake@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543223',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB013',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Hope',
				'last_name' => 'Demo',
				'unique_id' => 'PRV14',
				'email' => 'hope@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543224',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB014',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Jill',
				'last_name' => 'Demo',
				'unique_id' => 'PRV15',
				'email' => 'jill@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543225',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB015',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Blakey',
				'last_name' => 'Demo',
				'unique_id' => 'PRV16',
				'email' => 'blakey@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543226',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB016',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Laszlo',
				'last_name' => 'Demo',
				'unique_id' => 'PRV17',
				'email' => 'laszlo@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543227',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB017',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Aisla',
				'last_name' => 'Demo',
				'unique_id' => 'PRV18',
				'email' => 'aisla@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543228',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB018',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Merida',
				'last_name' => 'Demo',
				'unique_id' => 'PRV19',
				'email' => 'merida@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543229',
				'gender' => 'FEMALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB019',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Leia',
				'last_name' => 'Demo',
				'unique_id' => 'PRV20',
				'email' => 'leia@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543230',
				'gender' => 'FEMALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB020',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Voss',
				'last_name' => 'Demo',
				'unique_id' => 'PRV21',
				'email' => 'voss@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543231',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB021',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Lucinda',
				'last_name' => 'Demo',
				'unique_id' => 'PRV22',
				'email' => 'lucinda@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543232',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB022',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Melba',
				'last_name' => 'Demo',
				'unique_id' => 'PRV23',
				'email' => 'melba@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543233',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB023',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Clancy',
				'last_name' => 'Demo',
				'unique_id' => 'PRV24',
				'email' => 'clancy@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543234',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB024',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Hart',
				'last_name' => 'Demo',
				'unique_id' => 'PRV25',
				'email' => 'hart@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543235',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB025',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Chet',
				'last_name' => 'Demo',
				'unique_id' => 'PRV26',
				'email' => 'chet@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543236',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB026',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Win',
				'last_name' => 'Demo',
				'unique_id' => 'PRV27',
				'email' => 'win@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543237',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB027',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Coltran',
				'last_name' => 'Demo',
				'unique_id' => 'PRV28',
				'email' => 'coltran@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543238',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB028',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Tobiah',
				'last_name' => 'Demo',
				'unique_id' => 'PRV29',
				'email' => 'tobiah@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543239',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB029',
				'qrcode_url' =>'',
			],
			[
				'first_name' => 'Sybil',
				'last_name' => 'Demo',
				'unique_id' => 'PRV30',
				'email' => 'sybil@demo.com',
				'password' => Hash::make('123456'),
				'country_code' => '91',
				'iso2' => '91',
				'mobile' => '9876543240',
				'gender' => 'MALE',
				'status' => 'APPROVED',
				'is_online' => '0',
				'is_service' => '1',
				'is_document' => '1',
				'is_bankdetail' => '1',
				'latitude' => '13.00',
				'longitude' => '80.00',               
				'company_id' => $company,            
				'country_id' => $city->country_id,           
				'state_id' => $city->state_id,
				'city_id' => $city->id,
				'currency' => 'USD',
				'currency_symbol' => '$',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
				'picture' => 'http://lorempixel.com/512/512/business/Tranxit',
				'referral_unique_id' =>'9AB030',
				'qrcode_url' =>'',
			]
		];

		foreach ($providers as $provider) {
			Provider::create($provider);
		}

		Schema::enableForeignKeyConstraints();
	}
}
